import { redactText, redactSerial, type RedactionOptions } from "./redaction";
import { healthBand, countBySeverity } from "./health";
import type { Severity as PrismaSeverity } from "@prisma/client";

export const DISCLAIMER =
  "This report was generated by FirewallLens AI, an independent diagnostic assistant. It is NOT an official Palo Alto Networks tool and does not replace Palo Alto Networks TAC. Findings are heuristic and should be validated by a qualified engineer.";

interface ReportDevice {
  hostname: string | null;
  serialNumber: string | null;
  model: string | null;
  panosVersion: string | null;
  uptime: string | null;
  haStatus: string | null;
  panoramaManaged: boolean;
  lastCommitStatus: string | null;
}

interface ReportFinding {
  ruleId: string;
  severity: PrismaSeverity;
  category: string;
  title: string;
  description: string;
  impact: string;
  recommendation: string;
  confidence: number;
  evidenceJson: unknown;
}

export interface ReportInput {
  device: ReportDevice | null;
  findings: ReportFinding[];
  healthScore: number;
  summary: string;
  generatedAt: Date;
  redaction: RedactionOptions;
  redactSerials: boolean;
}

const SEV_ORDER: PrismaSeverity[] = ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFORMATIONAL"];

function sevLabel(s: PrismaSeverity): string {
  return s.charAt(0) + s.slice(1).toLowerCase();
}

function r(text: string | null | undefined, opts: RedactionOptions): string {
  if (!text) return "—";
  return redactText(text, opts);
}

function evidenceList(ev: unknown, opts: RedactionOptions): Array<{ filePath: string; snippet: string }> {
  if (!Array.isArray(ev)) return [];
  return ev.map((e) => ({
    filePath: String((e as { filePath?: string }).filePath ?? "—"),
    snippet: redactText(String((e as { snippet?: string }).snippet ?? ""), opts),
  }));
}

export function buildMarkdownReport(input: ReportInput): string {
  const { device, findings, healthScore, summary, redaction, redactSerials } = input;
  const band = healthBand(healthScore);
  const counts = countBySeverity(findings.map((f) => ({ severity: sevLabel(f.severity) as never })));
  const lines: string[] = [];

  lines.push(`# FirewallLens AI — Troubleshooting Report`);
  lines.push(`_Generated ${input.generatedAt.toISOString()}_`);
  lines.push("");
  lines.push(`> ${DISCLAIMER}`);
  lines.push("");

  lines.push(`## Device Summary`);
  if (device) {
    lines.push(`- **Hostname:** ${r(device.hostname, redaction)}`);
    lines.push(`- **Serial:** ${redactSerials ? redactSerial(device.serialNumber) : device.serialNumber ?? "—"}`);
    lines.push(`- **Model:** ${r(device.model, redaction)}`);
    lines.push(`- **PAN-OS:** ${r(device.panosVersion, redaction)}`);
    lines.push(`- **Uptime:** ${r(device.uptime, redaction)}`);
    lines.push(`- **HA Status:** ${r(device.haStatus, redaction)}`);
    lines.push(`- **Panorama Managed:** ${device.panoramaManaged ? "Yes" : "No"}`);
    lines.push(`- **Last Commit:** ${r(device.lastCommitStatus, redaction)}`);
  } else {
    lines.push("_No device information detected._");
  }
  lines.push("");

  lines.push(`## Health Score`);
  lines.push(`**${healthScore}/100 — ${band.label}**`);
  lines.push("");
  lines.push(`| Critical | High | Medium | Low | Info |`);
  lines.push(`|---|---|---|---|---|`);
  lines.push(`| ${counts.Critical} | ${counts.High} | ${counts.Medium} | ${counts.Low} | ${counts.Informational} |`);
  lines.push("");

  lines.push(`## Executive Summary`);
  lines.push(redactText(summary, redaction));
  lines.push("");

  lines.push(`## Findings`);
  for (const sev of SEV_ORDER) {
    const group = findings.filter((f) => f.severity === sev);
    if (group.length === 0) continue;
    lines.push(`### ${sevLabel(sev)} (${group.length})`);
    for (const f of group) {
      lines.push(`#### ${f.title}  \n\`${f.ruleId}\` · ${f.category} · Confidence ${f.confidence}%`);
      lines.push(`**Description:** ${redactText(f.description, redaction)}`);
      lines.push(`**Impact:** ${redactText(f.impact, redaction)}`);
      const ev = evidenceList(f.evidenceJson, redaction);
      if (ev.length) {
        lines.push(`**Evidence:**`);
        for (const e of ev) lines.push(`- \`${e.filePath}\`: ${e.snippet.replace(/\n/g, " ")}`);
      }
      lines.push(`**Recommendation:** ${redactText(f.recommendation, redaction)}`);
      lines.push("");
    }
  }

  lines.push(`---`);
  lines.push(`_${DISCLAIMER}_`);
  return lines.join("\n");
}

const SEV_COLORS: Record<PrismaSeverity, string> = {
  CRITICAL: "#dc2626",
  HIGH: "#ea580c",
  MEDIUM: "#ca8a04",
  LOW: "#2563eb",
  INFORMATIONAL: "#6b7280",
};

function esc(s: string): string {
  return s.replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]!));
}

export function buildHtmlReport(input: ReportInput): string {
  const { device, findings, healthScore, summary, redaction, redactSerials } = input;
  const band = healthBand(healthScore);
  const counts = countBySeverity(findings.map((f) => ({ severity: sevLabel(f.severity) as never })));

  const findingsHtml = SEV_ORDER.map((sev) => {
    const group = findings.filter((f) => f.severity === sev);
    if (group.length === 0) return "";
    const items = group
      .map((f) => {
        const ev = evidenceList(f.evidenceJson, redaction)
          .map((e) => `<li><code>${esc(e.filePath)}</code>: ${esc(e.snippet)}</li>`)
          .join("");
        return `<div class="finding">
          <h4><span class="pill" style="background:${SEV_COLORS[f.severity]}">${sevLabel(f.severity)}</span> ${esc(f.title)}</h4>
          <p class="meta"><code>${esc(f.ruleId)}</code> · ${esc(f.category)} · Confidence ${f.confidence}%</p>
          <p><strong>Description:</strong> ${esc(redactText(f.description, redaction))}</p>
          <p><strong>Impact:</strong> ${esc(redactText(f.impact, redaction))}</p>
          ${ev ? `<p><strong>Evidence:</strong></p><ul>${ev}</ul>` : ""}
          <p><strong>Recommendation:</strong> ${esc(redactText(f.recommendation, redaction))}</p>
        </div>`;
      })
      .join("");
    return `<section><h3>${sevLabel(sev)} (${group.length})</h3>${items}</section>`;
  }).join("");

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>FirewallLens AI Report</title>
<style>
  body{font-family:system-ui,Segoe UI,Arial,sans-serif;max-width:900px;margin:0 auto;padding:2rem;color:#111;line-height:1.5}
  h1{margin-bottom:.25rem} .sub{color:#666;font-size:.9rem}
  .disclaimer{background:#fff7ed;border:1px solid #fed7aa;border-radius:8px;padding:.75rem 1rem;font-size:.85rem;color:#9a3412;margin:1rem 0}
  table{border-collapse:collapse;width:100%;margin:.5rem 0}
  th,td{border:1px solid #e5e7eb;padding:.4rem .6rem;text-align:center}
  .score{font-size:2rem;font-weight:700}
  .band{display:inline-block;padding:.2rem .6rem;border-radius:999px;color:#fff;background:${SEV_COLORS[healthScore >= 75 ? "LOW" : healthScore >= 50 ? "MEDIUM" : healthScore >= 25 ? "HIGH" : "CRITICAL"]}}
  .finding{border:1px solid #e5e7eb;border-radius:8px;padding:1rem;margin:.75rem 0}
  .pill{color:#fff;padding:.1rem .5rem;border-radius:999px;font-size:.75rem;margin-right:.4rem}
  .meta{color:#666;font-size:.8rem} code{background:#f3f4f6;padding:.1rem .3rem;border-radius:4px}
  dl{display:grid;grid-template-columns:180px 1fr;gap:.25rem .75rem}
</style></head><body>
  <h1>FirewallLens AI</h1>
  <p class="sub">Troubleshooting Report · generated ${esc(input.generatedAt.toISOString())}</p>
  <div class="disclaimer">${esc(DISCLAIMER)}</div>

  <h2>Device Summary</h2>
  ${
    device
      ? `<dl>
    <dt>Hostname</dt><dd>${esc(r(device.hostname, redaction))}</dd>
    <dt>Serial</dt><dd>${esc(redactSerials ? redactSerial(device.serialNumber) : device.serialNumber ?? "—")}</dd>
    <dt>Model</dt><dd>${esc(r(device.model, redaction))}</dd>
    <dt>PAN-OS</dt><dd>${esc(r(device.panosVersion, redaction))}</dd>
    <dt>Uptime</dt><dd>${esc(r(device.uptime, redaction))}</dd>
    <dt>HA Status</dt><dd>${esc(r(device.haStatus, redaction))}</dd>
    <dt>Panorama Managed</dt><dd>${device.panoramaManaged ? "Yes" : "No"}</dd>
    <dt>Last Commit</dt><dd>${esc(r(device.lastCommitStatus, redaction))}</dd>
  </dl>`
      : "<p>No device information detected.</p>"
  }

  <h2>Health Score</h2>
  <p><span class="score">${healthScore}/100</span> <span class="band">${esc(band.label)}</span></p>
  <table><thead><tr><th>Critical</th><th>High</th><th>Medium</th><th>Low</th><th>Info</th></tr></thead>
  <tbody><tr><td>${counts.Critical}</td><td>${counts.High}</td><td>${counts.Medium}</td><td>${counts.Low}</td><td>${counts.Informational}</td></tr></tbody></table>

  <h2>Executive Summary</h2>
  <p>${esc(redactText(summary, redaction))}</p>

  <h2>Findings</h2>
  ${findingsHtml || "<p>No findings.</p>"}

  <hr/>
  <p class="sub">${esc(DISCLAIMER)}</p>
</body></html>`;
}
